// Auto-generated by scripts/sync-preset-fish-base64.mjs
// Source: remote preset fish URLs

export interface PresetFishBase64Entry {
    id: string;
    imageData: string;
}

export const PRESET_FISH_BASE64: PresetFishBase64Entry[] = [
    {
        id: "fish_0",
        imageData: "https://turing-test-1319469298.cos.ap-guangzhou.myqcloud.com/fish_0.png?imageSlim",
    },
    {
        id: "fish_1",
        imageData: "https://turing-test-1319469298.cos.ap-guangzhou.myqcloud.com/fish_1.png?imageSlim",
    },
    {
        id: "fish_2",
        imageData: "https://turing-test-1319469298.cos.ap-guangzhou.myqcloud.com/fish_2.png?imageSlim",
    },
];
